services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: support@doditech.com
      PGADMIN_DEFAULT_PASSWORD: Yopeyope20!
    ports:
      - "8082:80"

