version: '3'
services:
  ddt-jenkins:
    container_name: jenkins
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 40000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      # linux and macos only
      - /var/run/docker.sock:/var/run/docker.sock  # Mount docker socket
    restart: always
    privileged: true # Add privilèges to container

volumes:
  jenkins_home:
   name: "jenkins"
